### ISSUE TITLE
Unable to install this application on centos using ssh (putty)

### ISSUE THREAD

**Issue by kul1010** [andyet/SimpleWebRTC#591]
Hi,
Right now i am installing on my server using; using putty ssh on centos. So showing errors.
Nodejs version is 8.1.2

[pankaj.kulshrestha@www-test-01 SimpleWebRTC]$ sudo npm i

    git-validate@2.2.2 install /var/www/html/pankaj/nodejs_proj/SimpleWebRTC/node_modules/git-validate
    node bin/install

fs.js:641
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
^

Error: EACCES: permission denied, open '/var/www/html/pankaj/nodejs_proj/SimpleWebRTC/.git/hooks/pre-commit'
at Error (native)
at Object.fs.openSync (fs.js:641:18)
at Object.fs.writeFileSync (fs.js:1347:33)
at Object.exports.installHooks (/var/www/html/pankaj/nodejs_proj/SimpleWebRTC/node_modules/git-validate/lib/utils.js:248:12)
at Object. (/var/www/html/pankaj/nodejs_proj/SimpleWebRTC/node_modules/git-validate/bin/install.js:3:7)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
npm ERR! Linux 3.10.0-514.21.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "i"
npm ERR! node v6.10.3
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! git-validate@2.2.2 install: node bin/install
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-validate@2.2.2 install script 'node bin/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the git-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node bin/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs git-validate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls git-validate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /var/www/html/pankaj/nodejs_proj/SimpleWebRTC/npm-debug.log

**Comment by kul1010** [comment]
resolved. So u can close it.
