### ISSUE TITLE
 Failed to construct 'RTCPeerConnection': '$STUNSERVER_URL' 

### ISSUE THREAD

**Issue by ysfm** [andyet/SimpleWebRTC#701]
Uncaught DOMException: Failed to construct 'RTCPeerConnection': '$STUNSERVER_URL' is not a valid URL.
    at new WrappedRTCPeerConnection (blob:https://simplewebrtc.com/dd938c7d-9840-4a5a-9c8c-d23ae5816517:300:28)
    at new window.RTCPeerConnection (https://webrtc.github.io/adapter/adapter-4.2.2.js:1207:16)
    at new PeerConnection (https://simplewebrtc.com/latest-v3.js:7871:15)
    at new Peer (https://simplewebrtc.com/latest-v3.js:12414:15)
    at WebRTC.createPeer (https://simplewebrtc.com/latest-v3.js:13289:12)
    at Socket.<anonymous> (https://simplewebrtc.com/latest-v3.js:13017:44)
    at Socket.onack (https://simplewebrtc.com/latest-v3.js:10512:6)
    at Socket.onpacket (https://simplewebrtc.com/latest-v3.js:10437:12)
    at Manager.<anonymous> (https://simplewebrtc.com/latest-v3.js:374:15)
    at Manager.Emitter.emit (https://simplewebrtc.com/latest-v3.js:512:20)

I did not understand the problem. turn and stun server information is correct. I get the same error on my site and at your demo address.

**Comment by fippo** [comment]
you can reproduce this error in the console:
```
var pc = new RTCPeerConnection({iceServers: [{url: '$STUNSERVER_URL'}]})
```
You might want to check you are not passing the literal `$STUNSERVER_URL` which is certainly not a valid stun url.

**Comment by fippo** [comment]
oh, this turned out to be an issue with the sandbox server, see #702. Please don't use the sandbox server or if you do mention that you use it.
