### ISSUE TITLE
Failed to construct 'RTCPeerConnection': 'stun.l.google.com' is not one of the supported URL schemes 'stun'

### ISSUE THREAD

**Issue by ysfm** [andyet/SimpleWebRTC#708]
Uncaught DOMException: Failed to construct 'RTCPeerConnection': 'stun.l.google.com' is not one of the supported URL schemes 'stun', 'turn' or 'turns'.
    at new WrappedRTCPeerConnection (blob:https://simplewebrtc.com/d8178bcd-5b66-401b-80ee-d142fd4b1d89:300:28)
    at new window.RTCPeerConnection (https://webrtc.github.io/adapter/adapter-4.2.2.js:1207:16)
    at new PeerConnection (https://simplewebrtc.com/latest-v3.js:7871:15)
    at new Peer (https://simplewebrtc.com/latest-v3.js:12414:15)
    at WebRTC.createPeer (https://simplewebrtc.com/latest-v3.js:13289:12)
    at Socket.<anonymous> (https://simplewebrtc.com/latest-v3.js:13017:44)
    at Socket.onack (https://simplewebrtc.com/latest-v3.js:10512:6)
    at Socket.onpacket (https://simplewebrtc.com/latest-v3.js:10437:12)
    at Manager.<anonymous> (https://simplewebrtc.com/latest-v3.js:374:15)
    at Manager.Emitter.emit (https://simplewebrtc.com/latest-v3.js:512:20)

in all applications and the official demo gives this error.

**Comment by fippo** [comment]
the sandbox signaling server is slightly misconfigured again. Should be fixed later today

**Comment by eterweb** [comment]
Hi @fippo , 

The same problem continues. when will it be fixed?

**Comment by fippo** [comment]
its fixed now.
